== Testing Abidos C++

In the making chapter you can see how Abidos C++ is built, is very important 
that when we are development a new rule, or we are changing some of this rules
or maybe doing other hacking of the project, we should test that the new patches
has not introduced new fault.
indexterm:[test]
indexterm:[tests_run.pl]

.make test_run
image::images/chapter_testing_testing_1.{eps_svg}[align="center"]

=== Executing the tests

To run the testing process write this in a console:

----
cd processor
make test_run
----

This command internally invokes the script *scripts/tests_run.pl*; you would
call this script in a console but is a clumsy way of do it, because you must
pass it a lot of directories that make do for you.

[[test_run_output]]
.example of test_run output
----
abidos running suit tests [0.0.06] 
{
 executable_with_dir [.../processor/src/abidos]
 test_dir            [.../processor/test/]
 test_includes_dir   [.../processor/test_includes/]
 test_out dir        [.../processor/test_out/]
 abidos_working_dir  [.../processor/.abidos/]
 [t001.cpp]-> [OK] [t002.cpp]-> [OK] <1>
 ....
  -----------------------------------
  tests OK 17/17
  -----------------------------------
}
----
<1> this is the files test executed and her result.

This script generates these files in test_out/ directory:

.test_out files
[width="100%",cols="<,<",frame="topbot",options="header", grid="none"]
|===============================================================================
|File                  | Description
|out_t<number>.cpp.dot | UML diagram
|out_t<number>.cpp     | in the future these file will be like the input file
|out_t<number>.cpp.txt     | Abidos verbose output with Symbols table printed
|trace_t<number>.cpp.gv    | tree with the rules used by Abidos C++
|trace_t<number>.cpp_urls_pruned.gv | tree with rules and *click & go*
|prune.log               | shows how many nodes have been cut in
                           the prune process
|test_out.log            | shows all Abidos calls with his parameters
|===============================================================================

=== Hey wait a moment, testing files are C++ files!

Very clever that is, when Abidos parses a file it use a set of grammar tools
to do it, when i write a new rule i write a set of cpp testing files to check
that this rules are working correctly, this means:


//
* UML diagram, it is a hand made test; check the UML output of the test that
the testing process generated, for example to check the diagram of the previous
file:

----
xdot_run.py test_out/out_t001.cpp.dot
----

And you will see this diagram:

.out_t001.cpp.dot
image::images/chapter_testing_out_t001.cpp.{eps_svg}[align="center"]

//
* The Symbols table must has all the information that Abidos has parsed, this 
part until now is hand made you need see the output of the test and studying his
parts.

In the future this will be check automatically using the generating files like
test_out/out_t001.cpp, this file is generating from the symbols table, and if
this file have the same information than the original file the whole process
is all right. But so far this file has not all the original tokens... yes
exactly i have other priorities.

For now we can see the information gathered in the symbols table, for example in
this file *test/t001.cpp*:

----
class A
{
};

class B: public A
{
};
----

You can see his output in *test_out/out_t001.cpp.txt*:

----
 less test_out/out_t001.cpp.txt
 ....
 first[B]/.../t001.cpp:5 \
  id[258]->[IDENTIFIER] text[B] \
  type[265]->[CLASS_NAME] \ <1>
  class_key[300]->[CLASS] 
    {
      map_base_class
      {
        first[A]->[PUBLIC][A] <2>
      }
      map_friend_class
      {
        empty
      }
      vector_class_member [0]
      {
      }
      map_class_member [0]
      {
        empty
      }
      free_declarator
      {
      }
    }
 ....
----

<1> B token has bee processed with these information, the token is scanned like
an IDENTIFIER then the parser knows with the help of some rules that this token
should be a symbol of type=CLASS.

<2> Abidos knows than B is a class therefore Abidos checked if B has fathers
classes and there is A.

//
* Abidos generates another useful file for each cpp test file trace tree, in
this file we can see the rules executes by Abidos.
indexterm:[trace_graph]

.trace_t001.cpp_pruned.gv
image::images/chapter_testing_trace_t001.cpp_pruned.{eps_svg}[align="center"]

This tree is generates by Abidos C++ making process in *test_out/* when the
make test_run is executed.

One example is *test_out/trace_t001.cpp_pruned.gv*, you can read more about this
in the chapter trace, trace component is the part of Abidos that generates
annotated parse trees.

[NOTE]
====
You can see the version without pruning if you need more detailed history of the
syntactic rules used in the cpp file, just open *test_out/trace_t001.cpp.gv*.
====
indexterm:[annotated parse tree]

* Abidos must consume all the tokens scanned in the test file, when Abidos is
called from the test_run script *scripts/tests_run.pl* the call is like this:

-----
  /.../processor/src/abidos \
    --includes /.../processor/test_includes/ \
    --out_dir  /.../processor/test_out/ \
    --test_all_tokens_consumed_flag \ <1>
    --test_original \
    --ts_show \
    --verbose /.../processor/test/book_01.cpp \
      > /.../processor/test_out/out_book_01.cpp.txt
-----

<1> If all tokens has been processed and matched
generates in his output *##ALL_TOKENS_CONSUMED* then the script knows the cpp
file tested is OK. For this all the tokens in the tested file must bee processed
successfully in some grammar rules.

This is the only automated test you can see it in the begin of this chapter
figure <<test_run_output,test run output>>

=== Test files and what they testing

When Abidos C++ grows some new rules are wrote then some new test files are
rotten in order to test this new functionality and to preserve that this
new functionality is not broken in the future due to the introduction of more
rules or changes did in other rules, will see a useful catalog about
functionality and what test files use it.

[NOTE]
====
test files are in abidos/processor/test directory
====

.test files rules used
[width="70%",cols="s,^m,e",frame="topbot",options="header"]
|====

|functionality | file test | some important rules tested

|abstract class | t044.cpp | direct_declarator
indexterm:[abstract class]

|array | t046.cpp | consume_array_brackets
indexterm:[array]

|class access specifier | t010.cpp, t032.cpp | access_specifier
(PRIVATE, PROTECTED, PUBLIC)
indexterm:[access_specifier, PRIVATE, PROTECTED, PUBLIC]

|class declaration | t001.cpp, t002.cpp and almost all test files |
class_specifier
indexterm:[class_specifier]

|class simple inheritance| t001.cpp, t002.cpp | base_clause_opt, base_clause
indexterm:[simple inheritance, inheritance simple]
indexterm:[base_clause]

|class multiple inheritance | t002.cpp, t003.cpp | base_clause_opt, base_clause
indexterm:[multiple inheritance, inheritance multiple]

|constructor | t014.cpp, t030.cpp | function_definition, decl_specifier, type_specifier,
nested_name_specifier
indexterm:[constructor, nested_name_specifier]
indexterm:[function_definition]
indexterm:[type_specifier]

|compositions & aggregations | t023.cpp |
indexterm:[aggregations]
indexterm:[compositions]

|cv_qualifier | t026.cpp | decl_specifier, cv_qualifier
indexterm:[cv_qualifier]

|decl specifier  FRIEND| t022.cpp, t024.cpp, t027.cpp | decl_specifier
(FRIEND, TYPEDEF)
indexterm:[FRIEND]
indexterm:[TYPEDEF,typedef]

|default parameters values | t045.cpp | parameter_declaration
indexterm:[default parameters values]

|destructor | t015.cpp, t030.cpp | function_definition, direct_declarator, unqualified_id
indexterm:[destructor, unqualified_id]
indexterm:[unqualified_id]

|enum | t039.cpp | enum_specifier, enum_name
indexterm:[enum, enum_specifier, enum_name]

|extern | t046.cpp | extern
indexterm:[extern]

|extern_c | t042.cpp | extern_c
indexterm:[extern_c]

|free declarator | t004.cpp | declarator, member_declaration
indexterm:[declarator]
indexterm:[member_declaration]

|free declarator multiples decl | t008.cpp |decl_specifier_seq
indexterm:[decl multiples]

|free declarator multiples declarator | t008.cpp |decl_specifier_seq
indexterm:[declarator multiples]

|free function body | t011.cpp | function_definition, function_body
indexterm:[free function, function free]
indexterm:[function_body]

|function specifier | t021.cpp | function_specifier (INLINE, VIRTUAL, EXPLICIT)
indexterm:[function_specifier, INLINE, VIRTUAL, EXPLICIT]

|namespace | t037.cpp, t038.cpp | original_namespace_definition,
named_namespace_definition
indexterm:[namespace]

|namespace using| t046.cpp | using_directive
indexterm:[namespace, using_directive]

|default parameters values | t045.cpp | parameter_declaration
indexterm:[default parameters values]

|mangling class names | t028.cpp, t031.cpp |  class_name, nested_name_specifier
indexterm:[mangling]
indexterm:[nested_name_specifier]

|member variable declarator | t004.cpp, t006.cpp | member_declaration

|member function declarator | t005.cpp | member_declaration

|member function definition inside | t012.cpp | member_declaration,
function_definition, function_body

|member function definition inside with dummy body | t013.cpp |
member_declaration, function_definition, function_body

|member function definition outside  | t007.cpp, t016.cpp, t017.cpp, t018.cpp,
t029.cpp | member_declaration, function_definition, function_body

|parameter declaration | t006.cpp | parameter_declaration
indexterm:[parameter_declaration]

|parameter declaration multiples decl | t009.cpp | parameter_declaration,
decl_specifier

|parameter ellipsis | t007.cpp | ELLIPSIS_opt (...)
indexterm:[ELLIPSIS]

|pointer operator| t018.cpp | ptr_operator (*,&)
indexterm:[pointer]

|pre-declaration | t044.cpp |
indexterm:[pre-declaration]

|preprocessor include | t034.cpp | preprocessor_include
indexterm:[preprocessor, include]

|preprocessor | t040.cpp | #ifndef, #define, #endif
indexterm:[preprocessor, ifndef, define, endif]

|overloading operators | t045.cpp | operator_function_id, _operator
indexterm:[overloading operators, operator_function_id, _operator]

|static outside initialization | t043.cpp | storage_class_specifier,
init_declarator

|storage class specifier | t020.cpp | storage_class_specifier (AUTO, REGISTER,
STATIC, EXTERN, MUTABLE)
indexterm:[storage_class_specifier, AUTO, REGISTER, STATIC, EXTERN, MUTABLE]

|struct alignment | t046.cpp | direct_declarator
indexterm:[alignment]

|using class like a type | t025.cpp | decl_specifier, type_name
indexterm:[typename]

|template declaration | t035.cpp, t038.cpp | template_declaration, template_parameter
indexterm:[template]

|template instantiation | t036.cpp, t038.cpp | template_argument_list

|====


