== abidos_cpp_doc

Book, web and man documentation about my project abidos cpp.

The documentation is a asciidoc sources
http://powerman.name/doc/asciidoc

with them i will generate:

* book
** user_manual
** programmer_manual
* man
** user_manual
** programmer_manual
* web

this documentation will be inserted in abidos protect
https://github.com/fructu/abidos

== useful commands:

* make and view pdf:

 make clean; make; okular out/pdf/abidos_cpp_programmer_manual_cover.pdf &

* aspell to check grammar:

 aspell --lang "en_EN" --personal=./.aspell.en.pws --check abidos_cpp.txt
 aspell --lang "en_EN" --personal=./.aspelgel.en.pws --check README.txt


* make generate in out/ the pdf and web documentation

* to see aspell personal dictionary:
 aspell config personal-path
 ls -l /home/hevia/.aspell.*

white_list.txt -> .aspell.

* delete temporal files:
 find . -name "*.bak" -exec rm {} \;
 find . -name "*.new" -exec rm {} \;


== working with abidos

* first you need have executed:

  abidos_cpp/processor$ abidos_make_process.pl


Directories *abidos* and *abidos_cpp_doc* must bee in the same level of
directories.

* create a file like this:

 chapter_<chapter>/<name>_white_list.txt

make will scan this _white_list.txt files and generates:

 out/images/chapter_architecture_c_loader_uml_01.eps
 out/images/chapter_architecture_c_loader_uml_01.svg


therefore you can insert the image with:
 image::out/images/chapter_architecture_c_loader_uml_01.{eps_svg}[align="center"]

[NOTE]
In the image tag change before chapter */* to *_*

